{% set name = "mat4py" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat4py-{{ version }}.tar.gz
  sha256: 438927e6c16831a337596f593eb0b391c4cf6c982280b635ae412e80dff7fd07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - mat4py
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat4py
  summary: Load and save data in the Matlab (TM) MAT-file format.
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/nephics/mat4py

extra:
  recipe-maintainers:
    - goanpeca
